# Site settings
title: 기록 위키
url: "https://hwieun.github.io"
baseurl: ""
description: >
    두서없는 기록 위키

# My information
email: hwieun0104@gmail.com
author: hwieun 
profile: 개발자
github_username: Hwieun
comment-support: utterances

# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

whitelist:
  - jekyll-redirect-from

# permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
  wiki:
    output: true
    permalink: /:collection/:path/
  my_tags:
    output: true
    permalink: /tagged/:slug/

# Comment Service
giscus:
 repo: Hwieun/hwieun.github.io
 repo_id: SAMPLE-VALUE
 category: Announcements
 category_id: SAMPLE-VALUE

google_analytics:
  ua:
google_adsense:
  client:

blame: "https://github.com/Hwieun/hwieun.github.io/blame/master/_wiki"
edit: "https://github.com/Hwieun/hwieun.github.io/edit/master/_wiki"
issue: "https://github.com/Hwieun/hwieun.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]


compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

defaults:
  - 
    scope:
     path: ""
     type: my_tags
    values:
     layout: tagged
  -
    scope:
      path: ""
      type: wiki
    values:
      layout: wiki
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
    values:
      layout: default

permalink: /blog/:slug
future: false

exclude:
- README.md
- LICENSE

exclude: [vendor]

Blog: /blog
Wiki: /recent

# Add general links to site pages here
links:
  

# Add links for more focus here
# special_links:
#   "Search": https://duckduckgo.com
